#!/bin/bash
# nb: this specific release image is needed until we can build one with the out-of-tree provider support
export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE=quay.io/padillon/ash-release-mirror:latest
export CLUSTER_NAME=$(yq r install-config.yaml metadata.name)
export AZURE_REGION=ppe3
export SSH_KEY=$(yq r install-config.yaml sshKey | xargs)
export BASE_DOMAIN=$(yq r install-config.yaml baseDomain)
export TENANT_ID=$(az account show | jq -r .tenantId)
export SUBSCRIPTION_ID=$(az account show | jq -r .id)
export AAD_CLIENT_ID=$(jq -r .appId sp.json)
export AAD_CLIENT_SECRET=$(jq -r .password sp.json)